app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
from . import login_manager


class Category(db.Model):  # category table
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    description = db.Column(db.String(255))
    post = db.relationship('Post', backref='category', lazy='dynamic')

    def save_cat(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Category {self.name}'


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    hashed_pass = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_image_path = db.Column(db.String())
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.hashed_pass = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.hashed_pass, password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    def __repr__(self):
        return f'User {self.username}'


class Post(db.Model):  # post table
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    content = db.Column(db.Text)
    cat_id = db.Column(db.Integer, db.ForeignKey('categories.id'))
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)
    users_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    category_name = db.Column(db.String(255), index = True,nullable = False)
    def save_post(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Post {self.title}'


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()


    @classmethod
    def get_comments(cls,post_id):
        comments = Comment.query.filter_by(post_id=post_id).all()

        return comments


    def __repr__(self):
        return f'Comment {self.content}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, FileField, StringField, SubmitField, SelectField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import Required, Email, Length, EqualTo
from ..models import User
from wtforms import ValidationError

class PostForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    category = SelectField('Pitch Category', choices=[('Sales','Sales'),('Interview','Interview'),
    ('Elevator','Elevator'),('Promotion','Promotion'),('Personal','Personal'),
    ('Pickup-lines','Pickup-lines')],validators=[Required()])
    post = TextAreaField('Pitch', validators=[Required()])
    submit = SubmitField('Post Pitch')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CatForm(FlaskForm):
    name = StringField('Category Name', validators=[Required(), Length(1, 64)])
    submit = SubmitField('Submit')

class CommentsForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[Required()])
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

db = SQLAlchemy()
bootstrap = Bootstrap()
mail = Mail()
simple = SimpleMDE()
login_manager = LoginManager()

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos', IMAGES)


# creating the application

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    # Initializing flask extensions
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)

    mail.init_app(app)
    simple.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Registering the auth bluprints
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/user-account')

    # configure UploadSet
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect, url_for, abort, flash, request
from . import main
from flask_login import login_required, current_user

from app.models import User, Post, Category
from .. import db,photos
from .forms import UpdateProfile,CommentsForm,PostForm



@main.route('/')
def index():
    posts = Post.query.order_by(Post.date_posted.desc()).all()
    print(posts)
    return render_template('index.html', posts=posts)
@main.route('/posts')
def posts():
    posts = Post.query.all()
    sales = Post.query.filter_by(category_name="Sales")
    interview = Post.query.filter_by(category_name = 'Interview').all()
    elevator = Post.query.filter_by(category_name = 'Elevator').all()
    promotion = Post.query.filter_by(category_name = 'Promotion').all()
    personal = Post.query.filter_by(category_name = 'Personal').all()
    pickuplines = Post.query.filter_by(category_name = 'Pickuplines').all()


    title = 'PitchDom -  Welcome to PitchDom'
    return render_template('posts.html', title=title , posts = posts, sales=sales, interview = interview, 
    elevator = elevator,promotion = promotion, personal = personal, pickuplines = pickuplines )
@main.route('/addpost',methods = ['GET', 'POST'])
@login_required
def addposts():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        post = form.post.data
        category = form.category.data
        user_id = current_user
        new_pitch_object = Post( category_name=category,title=title,content=post)
        new_pitch_object.save_post()
        return redirect(url_for('main.addposts'))
        

        return(redirect(url_for('main.category')))
    title = 'Add-Post -  Welcome to PitchDom'
    return render_template('addpost.html', title=title, post_form=form)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)



@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/add_category', methods=['GET', 'POST'])
def add_cat():
    form = CatForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        flash('Category added successfully.')
        return redirect(url_for('.index'))
    return render_template('add_category.html', form=form)

app/templates/add_category.html
{% import "bootstrap/wtf.html" as wtf %}
{{ wtf.quick_form(form) }}

app/templates/addpost.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-8 pitch-form">
            <h2>Create a Pitch</h2>
            {{wtf.quick_form(post_form)}}
        </div>
    </div>
</div>

{% endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to pitchdom </title>
        {% endif %}
    </head>
    <body>
        <!-- Content block -->

        {% block content %}

        {% endblock%}


    </body>
</html>

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{%block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename= 'css/index.css')}}">
{%endblock %}
{% block content %}
 <body>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
    </div>
    {% endfor %}
    <div  class="container">

    {{wtf.quick_form(comment_form)}}
    
    </div>

    {% for comment in comment %}

    <p>{{ comment.content }}</p>

    {% endfor %}
  </body> 


{%endblock%}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 lh-lg">
            <h1 class="text-info">WELCOME TO PITCHDOM</h1>
            <p class="fw-bolder">If you only had one minute to impress someone, what would you do ?</p>
            <p>It may seem as an easy task but having 60 seconds to impress someone can be a hard task.
            </p>
            <p>You don't need to worry no more, you know why?</p>
            <p><b>Because here at Pitchdom we have you covered for that!!!</b></p>
            <a href="{{url_for('auth.register')}}" class="btn btn-outline-primary mt-4">Create Account</a>
        </div>
       
    </div>

    <!-- Services -->
    <div class="row mt-5">
        <hr>
        <div class="col-md-4 mt-4">
            <div class="card h-100" style="width: 18rem;">
                <div class="card-body">
                    <p class="card-title"><b>Let us expose your ideas to the world</b></p>
                    <p class="card-text">Create your own pitches and post them to see how the others will react to them.
                        The better the pitch the more likes you get.
                    </p>
                    <a href="{{url_for('main.addposts')}}" class="btn btn-outline-primary">Create a pitch</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mt-4">
            <div class="card h-100" style="width: 18rem;">
                <div class="card-body">
                    <p class="card-title"><b> Let us help you develop better pitching.</b></p>
                    <p class="card-text">Since you will have a chance to view other peoples pitches, this will be a
                        great environment for you to learn more from others.
                    </p>
                    <a href="{{url_for('auth.login')}}" class="btn btn-outline-primary">Login</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <div class="row mt-5">
        <hr>
        <div class="col-md-12">
            <footer>
                <p style="text-align: center"> Copyright &copy;
                    <script>document.write(new Date().getFullYear())</script> Pitches All Rights Reserved
                </p>
            </footer>
        </div>
    </div>


</div>

{% endblock %}

app/templates/macros.html
{% macro display(posts) %}
<div class="container-fluid">
	<div class="row">
		{% if posts %}
		{% for category in posts %}
		<div class="col-md-4">
			<div class="card">
				<h5 class="card-header bg-success">Pitch: {{category.title}}</h5>
				<div class="card-body">
					<p> {{category.post}}</p>
					<p> Category: {{category.category_name}}</p>
					<div><span class="footer">Content: {{category.content}}</span></div>
                    <p> Posted at: {{category.date_posted}}</p>
				</div>
			</div>
		</div>

		{% endfor %}
		{% else %}
		<div class="card w-90 mb-3">
			<div class="card-body">

				<p class="card-title">Category Has 0 posts</p>
			</div>
		</div>
		{% endif %}
	</div>
</div>
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse " role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> PITCHDOM </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
              <li class="user"><a href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a></li>
              <li><a href="{{url_for('main.addposts')}}" class="tag">Post Pitches</a></li>
              <li><a href="{{url_for('main.posts')}}" class="tag">View Pitches</a></li>
              <li><a href="{{url_for('auth.logout')}}">Log out</a></li>
              {% else %}
              <li><a href="{{url_for('auth.login')}}">Log in</a></li>
              {%endif%}
            </ul>
        </div>
    </div>
  </div>

app/templates/posts.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content%}
<div class="container" id="particles-js">
    <h2 class="text-center" id="posts">All Pitches</h2>
    <ul class="nav nav-pills nav-justified nav-fill" role="tablist">
        <li class="nav-item">
            <a id="cats" class="nav-link" data-toggle="tab" href="#all"><strong>All Pitches</strong> </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#sales">Sales Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#interview">Interview Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#elevator">Elevator Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#promotion">Promotion Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#personal">Personal Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#pickuplines">Pickup-lines Pitches</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="container tab-pane active" id="all"><br>
            {{ macro.display(posts) }}
        </div>
        <div class="container tab-pane fade" id="sales"><br>
            {{ macro.display(sales)}}
        </div>
        <div class="container tab-pane fade" id="interview"><br>
            {{ macro.display(interview) }}
        </div>
        <div class="container tab-pane fade" id="elevator"><br>
            {{ macro.display(elevator) }}
        </div>
        <div class="container tab-pane fade" id="promotion"><br>
            {{ macro.display(promotion) }}
        </div>
        <div class="container tab-pane fade" id="personal"><br>
            {{ macro.display(personal) }}
        </div>
        <div class="container tab-pane fade" id="pickuplines"><br>
            {{ macro.display(pickuplines) }}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/posts.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content%}
<div class="container" id="particles-js">
    <h2 class="text-center" id="posts">All Pitches</h2>
    <ul class="nav nav-pills nav-justified nav-fill" role="tablist">
        <li class="nav-item">
            <a id="cats" class="nav-link" data-toggle="tab" href="#all"><strong>All Pitches</strong> </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#sales">Sales Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#interview">Interview Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#elevator">Elevator Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#promotion">Promotion Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#personal">Personal Pitches</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="cats" data-toggle="tab" href="#pickuplines">Pickup-lines Pitches</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="container tab-pane active" id="all"><br>
            {{ macro.display(pitches) }}
        </div>
        <div class="container tab-pane fade" id="sales"><br>
            {{ macro.display(sales)}}
        </div>
        <div class="container tab-pane fade" id="interview"><br>
            {{ macro.display(interview) }}
        </div>
        <div class="container tab-pane fade" id="elevator"><br>
            {{ macro.display(elevator) }}
        </div>
        <div class="container tab-pane fade" id="promotion"><br>
            {{ macro.display(promotion) }}
        </div>
        <div class="container tab-pane fade" id="personal"><br>
            {{ macro.display(personal) }}
        </div>
        <div class="container tab-pane fade" id="pickuplines"><br>
            {{ macro.display(pickuplines) }}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <p> <b>{{user.username| capitalize}}</b> </p>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p>Username: {{user.username}}</p>
            <p>Bio: {{user.bio}}</p>
            <p>Email: {{user.email}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}" class="btn btn-outline-primary">Edit profile</a>
            {% endif %}

        </div>

        <!--Display profile photo-->
        <div class="col-md-4">
            {% if user.profile_image_path %}
        
            <img src="{{url_for('static',filename=user.profile_image_path)}}" alt="" class="img-thumbnail">
        
            {%else%}
            <p>No profile picture</p>
        
            {% endif %}
        
                {% if user == current_user %}
            <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
        
              <input type="file"  name="photo" class="form-control" required>
              <input type="submit">
            </form>
              {% endif %}
          </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}